apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
  namespace: microservices
data:
  PORT: "3003"
  MONGO_URI: "mongodb://admin:password123@mongodb-service.mongodb.svc.cluster.local:27017/notificationdb?authSource=admin"
